[dev]
  command = "pnpm dev"
  framework = "astro"

[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions/"

# 🚧 MODO MANTENIMIENTO
[[redirects]]
  from = "/*"
  to = "/mantenimiento"
  status = 302
